### ISSUE TITLE
body font-family overrides styles.

### ISSUE THREAD

**Issue by vssn** [paul-straetmans/nice-html-with-css#7]
Hi @paul-straetmans,
it looks like the following style definition is overriding font styles in my website when applying the distributed css. Is it required?

index.scss Line 53
```
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica,
    Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
}
```

**Comment by paul-straetmans** [comment]
@vssn that should not happen of course 👍 I'll take a look at it

**Comment by paul-straetmans** [comment]
@vssn a class is added to the demo template. Now the body styles are only added to the demo template.
